### ISSUE TITLE
能不能在Unreal的rpc调用当中利用sproto作为参数传递信息？

### ISSUE THREAD

**Issue by futouyiba** [zhangweiiscoding/UnLuaWithLibs#2]
省得在c++里来回写结构体定义、重新编译。

**Comment by zhangweiiscoding** [comment]
> 省得在c++里来回写结构体定义、重新编译。

群里回答你了，可以考虑用cjson来解析lua table来encode decode。因为不确定ue4 rpc的性能，所以现在的项目用的skynet服务端。想请教下有测试过ue4 rpc的性能吗，在高并发情况下的响应时间之类的。如果理想的话后面的项目会使用你这个方案。
